config/routes.rb
Rails.application.routes.draw do
  get "/routes/search", to: "routes#search", as: "routes_search"

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :projects
  resources :grades
  resources :routes do
    resources :comments
  end

  scope :auth do
    get 'is_signed_in', to: 'users#is_signed_in?'
    get 'current', to: 'users#current'
  end

  get "users/:id" => "users#show", as: "user"
  get "users/:user_id/comments" => "users/comments#index", as: "user_comments"
  delete "users/:user_id/comment/:id" => "users/comments#destroy", as: "destroy_user_comment"

  get "users/:user_id/routes" => "users/routes#index", as: "user_routes"
  delete "users/:user_id/route/:id" => "users/routes#destroy", as: "destroy_user_route"

  get "users/:user_id/projects" => "users/projects#index", as: "user_projects"
  delete "users/:user_id/project/:id" => "users/projects#destroy", as: "destroy_user_project"
  
  root 'main#dashboard'


end

app/models/route.rb
class Route < ActiveRecord::Base
	belongs_to :grade
	has_many :users, through: :projects
	has_many :projects
	has_many :comments
	belongs_to :owner, class_name: "User", foreign_key: "owner_id"

	validates_presence_of :grade_id
	validates_presence_of :owner_id
  validates_numericality_of :grade_id

  after_save :load_into_soulmate

  def load_into_soulmate
    loader = Soulmate::Loader.new("route")
    loader.add(
      "term" => name,
      "id" => id,
      "grade" => grade.name,
      "url" => Rails.application.routes.url_helpers.route_path(self)
      )
  end

  def remove_from_soulmate
    loader = Soulmate::Loader.new("route")
    loader.remove("id" => id)
  end

  def self.search(term)
    matches = Soulmate::Matcher.new('route').matches_for_term(term)
    matches.collect do |match|
      {
        "id" => match["id"],
        "label" => match["term"],
        "value" => match["term"],
        "grade" => match["grade"],
        "url" => match["url"]
      }
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_user_is_owner, only: [:edit, :update, :destroy]

  def index
    @routes = Route.includes(:grade).all.map {|r| PartialRouteSerializer.new(r, root: false)}
    respond_to do |format|
      format.html
      format.json { render json: @routes, root: false }
    end
  end

  def show
    @projects = @route.projects
    @grade    = @route.grade
    @comments = @route.comments
    respond_to do |format|
      format.html
      format.json { render json: @route }
    end
  end

  def search
    render :json => Route.search(params['term']), root: false
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params.merge("owner_id" => current_user.id))
    
    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render json: @route, status: :created }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_route
    @route = Route.find(params[:id])
  end

  def require_user
    if current_user.nil?
      flash[:notice] = "You must be logged in to view this page"
      redirect_to routes_path
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def route_params
    params.require(:route).permit(:name, :grade_id, :owner_id, :info)
  end

  def require_user_is_owner
    if current_user != @route.owner
      flash[:notice] = "You are not authorized to perform this action"
      redirect_to routes_path
    end
  end
end

app/controllers/users/routes_controller.rb
class Users::RoutesController < ApplicationController
  before_action :require_user_is_owner, only: :destroy

  def index
    @user = User.find(params[:user_id])
    @routes = @user.routes.map {|r| PartialRouteSerializer.new(r, root: false)}
    respond_to do |format|
      format.html
      format.json { render json: @routes, root: false }
    end
  end

  def destroy
    @route = Route.find(params[:id])
    @route.destroy
    respond_to do |format|
      format.html { redirect_to user_routes_path(current_user), notice: 'Route has been deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def require_user_is_owner
    if current_user.id != params[:user_id].to_i
      flash[:notice] = "You are not authorized to perform this action"
      redirect_to root_path
    end
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %><br>
    <%= f.label :info %><br>
    <%= f.text_area :info %><br>
    <%= f.hidden_field :owner_id, value: current_user.id %>
    <%= f.collection_select(:grade_id, Grade.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<h3>All routes</h3>

<script type="text/babel">
  ReactDOM.render(
    <RouteList url="/routes" pollInterval="5000" />,
    document.getElementById('content')
  );
</script>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @route.name %></strong> (<%= link_to @grade.name, @grade %>)
</p>

<p><strong>Created by: </strong><%= link_to @route.owner.name, @route.owner %></p>

<p><strong>Info: </strong><%= @route.info %></p>

<h3>People projecting this route:</h3>

<table>
	<tr>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @projects.each do |project| %>
		<tr>
			<td><%= link_to project.user.name, project.user %></td>
			<td><%= project.created_at %></td>
			<td><%= project.status %></td>
		</tr>
	<% end %>
</table>

<h3>Comments:</h3>

<table>
	<tr>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @comments.each do |comment| %>
		<tr>
			<td><%= link_to comment.user.name, comment.user %></td>
			<td><%= comment.body %></td>
			<td><%= comment.created_at %></td>
			<% if current_user == comment.user %>
				<td><%= link_to "Delete", route_comment_path(@route, comment, user_id: current_user.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<% end %>
		</tr>
	<% end %>
</table>

<% if current_user %>
	<p><%= link_to "New Comment", new_route_comment_path(@route.id) %></p>
<% end %>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>