config/routes.rb
Rails.application.routes.draw do
  get "/routes/search", to: "routes#search", as: "routes_search"

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :projects
  resources :grades
  resources :routes do
    resources :comments
  end

  scope :auth do
    get 'is_signed_in', to: 'users#is_signed_in?'
    get 'current', to: 'users#current'
  end

  get "users/:id" => "users#show", as: "user"
  get "users/:user_id/comments" => "users/comments#index", as: "user_comments"
  delete "users/:user_id/comment/:id" => "users/comments#destroy", as: "destroy_user_comment"

  get "users/:user_id/routes" => "users/routes#index", as: "user_routes"
  delete "users/:user_id/route/:id" => "users/routes#destroy", as: "destroy_user_route"

  get "users/:user_id/projects" => "users/projects#index", as: "user_projects"
  delete "users/:user_id/project/:id" => "users/projects#destroy", as: "destroy_user_project"
  
  root 'main#dashboard'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sendero</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react-router/0.11.6/react-router.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Dashboard", root_path %></li>
    <li class="navbar-form navbar-left" role="search">
      <%= text_field_tag 'search_box', nil, placeholder: "Search" %>
    </li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>
</div>


<p id="notice"><%= notice %></p>

<div id='content'></div>

<%= yield %>

<!-- Logic for search box -->

<script type="text/javascript">

  $(function() {
    
    $('#search_box').autocomplete({
      minLength: 2,
      source: '<%= routes_search_path(:json) %>',

      focus: function(event, ui) {
        $('#search_box').val(ui.item.value);
        return false;
      },

      select: function(event, ui) {
        $('#search_box').val(ui.item.value);
        $('#link_origin_id').val(ui.item.id);
        return false;
      }}).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
        console.log(item);
        return $("<li></li>")
          .data( "autocomplete-item", item )
          .append("<div>" +
            "<a href=" + item.url + ">" + item.value + " (" + item.grade + ")" + "</a>" +
            "</div>")
          .appendTo( ul );
    };
  });
</script>

</body>
</html>